Time::DATE_FORMATS[:month_day_year] = "%b %d, %Y"
Time::DATE_FORMATS[:long_with_zone] = "%b %-d, %Y at %I:%M%P %Z"
Time::DATE_FORMATS[:day_at_time] = "%-d %b @ %H:%M"
Time::DATE_FORMATS[:month_day] = "%b %d"
Time::DATE_FORMATS[:db_just_date] = "%Y-%m-%d"
Time::DATE_FORMATS[:event_day] = "%A, %b %d"
Time::DATE_FORMATS[:time_p] = "%l:%M %P"
