on:
  push:
    branches:
      - kaigionrails

jobs:
  build:
    runs-on: ubuntu-latest
    if: "${{ github.repository == 'kaigionrails/cfp-app' }}"
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      - uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
        with:
          aws-region: ap-northeast-1
          role-skip-session-tagging: false
          role-to-assume: "arn:aws:iam::861452569180:role/GhaDockerPushToEcr"
      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2.1.6
      - id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          images: "${{ steps.login-ecr.outputs.registry }}/cfp-app"
          tags: |
            type=sha,format=long,prefix=
            type=raw,value=latest
      - uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: "."
          platforms: linux/amd64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://cfp.kaigionrails.org
    concurrency:
      group: "deploy"
      cancel-in-progress: false
    needs: ["build"]
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
        with:
          bundler-cache: true
      - uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
        with:
          aws-region: ap-northeast-1
          role-skip-session-tagging: false
          role-to-assume: "arn:aws:iam::861452569180:role/CfpAppDeployer"
      - name: Set up SSH key and known_hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$KAMAL_SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "$KAMAL_KNOWN_HOSTS" >> ~/.ssh/known_hosts
        env:
          KAMAL_SSH_PRIVATE_KEY: ${{ secrets.KAMAL_SSH_PRIVATE_KEY }}
          KAMAL_KNOWN_HOSTS: ${{ secrets.KAMAL_KNOWN_HOSTS }}
      - run: bundle exec kamal deploy --skip-push --version=${{ github.sha }}
        env:
          KAMAL_WEB_SERVER_ADDRESS: ${{ secrets.KAMAL_WEB_SERVER_ADDRESS }}
          KAMAL_WEB_SERVER_PRIVATE_ADDRESS: ${{ secrets.KAMAL_WEB_SERVER_PRIVATE_ADDRESS }}
