on:
  push:
    branches:
      # - kaigionrails
      - "kaigionrails2025"
jobs:
  build:
    runs-on: ubuntu-latest
    if: "${{ github.repository == 'kaigionrails/cfp-app' }}"
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      - uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6.1.1
        with:
          aws-region: us-west-2
          role-skip-session-tagging: false
          role-to-assume: "arn:aws:iam::861452569180:role/GhaDockerPushToEcr"
      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@fa648b43de3d4d023bcb3f89ed6940096949c419 # v2.1.5
      - id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: "${{ steps.login-ecr.outputs.registry }}/cfp-app"
          tags: |
            type=sha,format=long,prefix=
            type=raw,value=latest
      - uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          context: "."
          platforms: linux/amd64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}

  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: "deploy"
      cancel-in-progress: false
    needs: ["build"]
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: us-west-2
    steps:
      - run: sudo apt-get update && sudo apt-get install jsonnet
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6.1.1
        with:
          aws-region: us-west-2
          role-skip-session-tagging: false
          role-to-assume: "arn:aws:iam::861452569180:role/CfpAppDeployer"
      - uses: kayac/ecspresso@3d47a637a1f8f2dd5c91bb616ac4b7a0e55b18ca # v2.8.4
        with:
          version: latest
      - run: ecspresso run --config deploy/ecspresso.jsonnet --ext-str IMAGE_SHA=${{ github.sha }} --overrides-file deploy/runtask-db-migrate.jsonnet
      - run: ecspresso deploy --config deploy/ecspresso.jsonnet --ext-str IMAGE_SHA=${{ github.sha }}
      - run: jsonnet deploy/apprunner.jsonnet --ext-str IMAGE_SHA=${{ github.sha }} > deploy/apprunner.json
      - run: aws apprunner update-service --cli-input-json file://deploy/apprunner.json
